var topics = [
  "business-transfer",
  "changes",
  "changes-involvement",
  "changes-notice",
  "cookies",
  "copyright-scope",
  "data-export",
  "governance",
  "guarantee",
  "jurisdiction-law",
  "law-enforcement",
  "law-gov",
  "leave",
  "logs-length",
  "ownership",
  "personal information",
  "personal-data",
  "readability",
  "scope of the copyright license",
  "suspension",
  "third",
  "track",
  "tracking",
  "user-choice",
  "user-info",
  "waiver"
];
